# Generated by Django 2.2.2 on 2019-06-29 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0002_readdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readdetail',
            old_name='read_mun',
            new_name='read_num',
        ),
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 29, 10, 23, 31, 440001)),
        ),
    ]
