# Generated by Django 2.2.2 on 2019-06-29 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0004_auto_20190629_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readnum',
            old_name='read_mun',
            new_name='read_num',
        ),
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 29, 13, 50, 2, 976417)),
        ),
    ]
